# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de9419dadaaa566124936db4051a488e63c1967626e2567e7b0dfb69a981d4169c6b460f2fe51d73dd3f468bcf5b70971374ac494860e8e0bf8065f1d16fcfe

test:
  secret_key_base: 8da2eedbf9a10f1696476a276bbe84341595d6a45eedc10543d40bf879c5265fa2f6a3f63fad773588234579587c6f2f8284282f4874be7fd8dd6c075178f35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
